### ISSUE TITLE
Update Github Actions for STIG compliance

### ISSUE THREAD

**Issue by bpmooch** [render-se/PX4-Autopilot#1]
The regular PX4 project has a bunch of GitHub Actions that they utilize. We need to remove all of these so we can run our own GitHub actions that support our STIG process.

First issues to solve is that gathering the test results is a manual process right now. Automating these steps will save enormous amounts of time moving forward. The following commands comprise what's currently done.

```
make cppcheck_px4_fmu-v5
make scan-build
make clang-tidy_px4_fmu-v5
make tests TESTFILTER=unit
make tests TESTFILTER=functional
test/mavsdk_tests/mavsdk_test_runner.py test/mavsdk_tests/configs/sitl.json --speed-factor 10
/usr/bin/genhtml lcov.info --output-directory out
```

- [x] Review current github actions to ensure we want to remove all of them
- [x] write bash script to automate the running of the commands above and capture their output
- [ ] How would we integrate this process upstream?
- [x] #6

**Comment by jrn90** [comment]
This has been updated & moved to [here](https://github.com/render-se/SRA/issues/69). Nice.
