### ISSUE TITLE
Package custom firmware in stand-alone format

### ISSUE THREAD

**Issue by jrn90** [render-se/PX4-Autopilot#13]
We need a way to package the firmware in a stand alone way that is easy to download & run. Downloading the entire PX4 project from github and setting it up is too cumbersome if the user just wants to flash the drone.

- [x] Find the minimum files needed in order to flash firmware
- [x] Find a way to create firmware and share with users

**Comment by bpmooch** [comment]
seems like we should use onedrive for this

**Comment by jrn90** [comment]
We are going to manually upload to a OneDrive folder & notify the flight tester that a new custom firmware version is available.
