### ISSUE TITLE
Document PX4 Make Build Process & Folder Structure

### ISSUE THREAD

**Issue by bpmooch** [render-se/PX4-Autopilot#14]
The purpose of this ticket is to create a better understanding of how PX4-Autopilot serves as a build system for Pixhawk standard compatible boards. Information should make it into a wiki as this stuff is internal to the team.

## Acceptance Criteria
- [x] #22
- [x] #21
- [x] #19
- [x] #16
- [x] #20
- [x] #15
- [x] #17

**Comment by jrn90** [comment]
Complete. Relevant & useful information has been captured in the [SRA Wiki](https://github.com/render-se/SRA/wiki/)
