### ISSUE TITLE
clang-tidy to do's

### ISSUE THREAD

**Issue by bpmooch** [render-se/PX4-Autopilot#2]
There are a bunch of TODO's for the clang-tidy px4_fmu-v5 target that need to be cleaned up. They are mainly compiler flags that clang-tidy was complaining about.

Note: maybe look into clang/gcc versions

- [ ] clean up todo's
- [x] If compiler versions were changed, why aren't they changed upstream?

**Comment by jrn90** [comment]
PX4 runs clang-tidy 6.0 instead of the latest version. When using clang-tidy 6.0 there are no compilation errors.

TODO's should be removed. Files changed should be reverted to master.

**Comment by jrn90** [comment]
>     * [x]  If compiler versions were changed, why aren't they changed upstream?

Turns out to be an issue with the clang-tidy version instead of gcc versions.

**Comment by jrn90** [comment]
This issue is stale. Running with the correct version of clang tidy and correct compiler flags allow this to work. No code changes are needed. Target board `fmu-v5` will be changed in future versions.
