### ISSUE TITLE
Script: Automate Test Results

### ISSUE THREAD

**Issue by jrn90** [render-se/PX4-Autopilot#6]
Gathering the test results is a manual process right now. Automating these steps will save enormous amounts of time moving forward
```
make cppcheck_px4_fmu-v5 
make scan-build 
make clang-tidy_px4_fmu-v5 
make tests TESTFILTER=unit 
make tests TESTFILTER=functional 
test/mavsdk_tests/mavsdk_test_runner.py test/mavsdk_tests/configs/sitl.json --speed-factor 10 
/usr/bin/genhtml lcov.info --output-directory out 
```

- [ ] Create scripts to automate running these commands
- [ ] Capture results of tests into an artifact (tar or zip)

**Comment by bpmooch** [comment]
to be moved
